// document.write('<script type="text/javascript" src="mandelbrot.js"></script>');
// document.write('<br><br>');
document.write('<div id="nav">');
document.write('<a href="index.html">Intro</a>');
document.write('<a href="essays.html">Essays</a>');
document.write('<a href="memos.html">Memos</a>');
document.write('<a href="notes.html">Notes</a>');
document.write('<a href="etc.html">Etc</a>');
document.write('</div>');
document.write('<br><br>');
